### ISSUE TITLE
Keys() for enumerating keys in the store

### ISSUE THREAD

**Issue by philips** [sethvargo/go-limiter#13]
For generating monitoring metrics, say to export to prometheus, it would be nice to be able to enumerate the keys in the store. An interface as simple as this would be fine with me:

```
type Store interface {
    Keys() string[]
}
```

This interface with a Peek (#11) would make it possible to implement metrics, I think.

**Comment by sethvargo** [comment]
Hey Brandon - that seems fine, but I'm a bit worried about the lock contention as we'd need to lock the entire map, build a new data structure with all the string keys, and return that. Given the focus on performance, that could get expensive, especially if you're calling Keys() frequently.

Are you interested in the specific keys or the _number_ of keys? Having a `Size()` or `NumKeys()` would be much more efficient because we can just grab the size of the map and avoid the extra allocation of the `[]string`.

**Comment by philips** [comment]
I would probably do the operation every 30 seconds or something like that.

I suppose the thing I am most interested in is keys that hit a ratelimit.
So, I could just keep a separate data structure.

I think I will close this for now and just see if rate limit hits is enough
visibility.

**Comment by sethvargo** [comment]
Okay sounds good - I'm definitely interested in making this flexible and extensible 😄
